### ISSUE TITLE
Несовместимость с EU4Encoding.exe

### ISSUE THREAD

**Issue by Feas2016** [exetwezz/EU4Localisation_HelpTools#1]
Само ПО: http://www.strategium.ru/forum/index.php?showtopic=48445

Берем файл: http://i.imgur.com/uWoO1yy.png
Декодируем: http://i.imgur.com/oydDw7I.png
Все норм.
Кодируем получившийся декодированный файл с данным ПО.
Результат: http://i.imgur.com/Z7Tw5MH.png
Сами файлы: [Несовместимость с EU4Encoding.zip](https://github.com/exetwezz/EU4Localisation_HelpTools/files/222253/EU4Encoding.zip)

**Comment by Feas2016** [comment]
Ожидаемый результат: http://i.imgur.com/OPYObNC.png

**Comment by exetwezz** [comment]
Не ошибка ли самого ПО?

И вообще причем тут HelpTools? Я так понимаю, что вы взяли [

**Comment by exetwezz** [comment]
Не ошибка ли самого ПО?

Насколько я понимаю, в данном случае это косяк не HelpTools, а как раз-таки `EU4Encoding.exe`, потому что HelpTools задевает только русские символы и их используемые в игре аналоги, а эти самые символы локализации (которые слева от `:`) написаны латинскими буквами.

**Comment by Feas2016** [comment]
Этим ПО мы пользуемся давно и оно работает нормально со своими же файлами. Я так понимаю разный декодированный продукт получается от одного и другого ПО. К сожалению править EU4Encoding.exe не представляется возможным.

Да, левая колонка ломается =(

Тут одно из двух, либо делать конечный продукт одинаковым, либо копировать его функционал т.е. его "кодирование" добавить.в этот кодировщик.

**Comment by exetwezz** [comment]
Да, согласен, эта программа работает замечательно. Но когда я пытался кодировать/декодировать локализационные файлы одного мода, русские символы в игре отображались так же, как и в кодированных файлах. Если я правильно понимаю, то эта программа требует особого шрифта для их отображения. Но я об этом не знал и поэтому и решил создать другую версию, так сказать "рабочую".

И я бы с удовольствием включил её функционал в этот репозиторий, но по ясной причине не могу. Конечный продукт делать одинаковым нет смысла — пропадёт нужда в этом репозитории.

**Comment by Feas2016** [comment]
А так можно сделать?
http://i.imgur.com/toBorX9.png

З.Ы. Конечный при декодировании имел ввиду.

**Comment by exetwezz** [comment]
Разумеется, можно.

Для начала мне нужно уточнить: объясните мне, пожалуйста, по какому фактору вы разделили на Lite и Full?

**Comment by exetwezz** [comment]
Хм, кажется и Lite, и Full оба используют специальные шрифты. Нужно проверить, будет ли работать локализация, если убрать их? (Переименовать `gfx/fonts` во что-нибудь и почистить кэш.)

У меня сейчас нет доступа к Windows и игре. Прошу вас протестирировать, пожалуйста.

**Comment by Feas2016** [comment]
Если удалить из русиков папку gfx и gfx из кеша имеем.

LITE перевод: ![20160416220539_1](https://cloud.githubusercontent.com/assets/13850023/14583066/5b08710c-041f-11e6-8d9d-8fdc0f319331.jpg)
FULL перевод: ![20160416220234_1](https://cloud.githubusercontent.com/assets/13850023/14583067/5b08bb62-041f-11e6-9fc4-155009182564.jpg)

> Upd: А то я не слишком понимаю различия между ними на техническом уровне.
Вы сделали перевод для Lite перевода.
Я же как раз в начале темы сделал попытку перевести в FULL из LITE

Вот ссылочка чтоб скачать в обход стима, удобно если игры нет под рукой: 
http://steamworkshopdownloader.com/view/227909442
http://steamworkshopdownloader.com/view/266053242

**Comment by exetwezz** [comment]
@Feas2016,

Спасибо вам большое за пояснение! Я понял, что вы имели в виду и что вы хотите.

В скором времени добавлю предложенный функционал.
> А так можно сделать?
> http://i.imgur.com/toBorX9.png

**Comment by Feas2016** [comment]
Это вам спасибо =)
